name: CI

on:
  push:

jobs:
  build:
    name: "AlmaLinux 8 / humble"
    runs-on: ubuntu-latest
    container:
      image: almalinux:8

    steps:
      - uses: ros-tooling/setup-ros@v0.7

      - name: generate repos file
        run: |
          cat << EOF > sources.repos
          repositories:
            src/examples:
              type: git
              url: https://github.com/ros2/examples.git
              version: humble
          EOF

      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: examples_rclcpp_minimal_publisher
          target-ros2-distro: humble
          vcs-repo-file-url: sources.repos
